apiVersion: apps/v1
kind: Deployment        # Type of Kubernetes resource
metadata:
  name: db
  labels:            # Labels that will be applied to this resource
    app: db
spec:
  selector:
    matchLabels:
      app: db
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: db # can be any key value pair
    spec:
      containers:
      - name: db
        image: postgres:10.4
        imagePullPolicy: "IfNotPresent"
        ports:
          - containerPort: 5432
# ---------------------

kind: Namespace
apiVersion: v1
metadata:
  name: testnamespace

# ----------------------

kind: ConfigMap
apiVersion: v1
metadata:
  namespace: testnamespace
  name: poststarthook
data:
  poststart.sh: |
     #!/bin/bash
     echo "It`s done"
