apiVersion: apps/v1
kind: Deployment        # Type of Kubernetes resource
metadata:
  name: db
spec:
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: db # can be any key value pair
    spec:
      containers:
      - name: db
        image: postgres:10.4
        imagePullPolicy: "IfNotPresent"
        ports:
          - containerPort: 5432
        envFrom:
          - configMapRef:
              name: postgres-config
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: test-volume
      volumes:
      - name: test-volume
        persistentVolumeClaim:
          claimName: postgres-pv-claim
  selector:
    matchLabels:
      app: db