// Code generated by MockGen. DO NOT EDIT.
// Source: sqlservices_interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/suprageeks/tech-task/pkg/models"
)

// MockISQLService is a mock of ISQLService interface.
type MockISQLService struct {
	ctrl     *gomock.Controller
	recorder *MockISQLServiceMockRecorder
}

// MockISQLServiceMockRecorder is the mock recorder for MockISQLService.
type MockISQLServiceMockRecorder struct {
	mock *MockISQLService
}

// NewMockISQLService creates a new mock instance.
func NewMockISQLService(ctrl *gomock.Controller) *MockISQLService {
	mock := &MockISQLService{ctrl: ctrl}
	mock.recorder = &MockISQLServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISQLService) EXPECT() *MockISQLServiceMockRecorder {
	return m.recorder
}

// DeleteBank mocks base method.
func (m *MockISQLService) DeleteBank(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBank", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBank indicates an expected call of DeleteBank.
func (mr *MockISQLServiceMockRecorder) DeleteBank(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBank", reflect.TypeOf((*MockISQLService)(nil).DeleteBank), id)
}

// GetAccountDetails mocks base method.
func (m *MockISQLService) GetAccountDetails(id string) (*models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountDetails", id)
	ret0, _ := ret[0].(*models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountDetails indicates an expected call of GetAccountDetails.
func (mr *MockISQLServiceMockRecorder) GetAccountDetails(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountDetails", reflect.TypeOf((*MockISQLService)(nil).GetAccountDetails), id)
}

// GetBankDetails mocks base method.
func (m *MockISQLService) GetBankDetails(id string) (*models.Bank, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBankDetails", id)
	ret0, _ := ret[0].(*models.Bank)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBankDetails indicates an expected call of GetBankDetails.
func (mr *MockISQLServiceMockRecorder) GetBankDetails(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBankDetails", reflect.TypeOf((*MockISQLService)(nil).GetBankDetails), id)
}

// ListAllBanks mocks base method.
func (m *MockISQLService) ListAllBanks() ([]*models.Bank, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllBanks")
	ret0, _ := ret[0].([]*models.Bank)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllBanks indicates an expected call of ListAllBanks.
func (mr *MockISQLServiceMockRecorder) ListAllBanks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllBanks", reflect.TypeOf((*MockISQLService)(nil).ListAllBanks))
}

// PatchBankDetails mocks base method.
func (m *MockISQLService) PatchBankDetails(id string, bankDetails models.Bank) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchBankDetails", id, bankDetails)
	ret0, _ := ret[0].(error)
	return ret0
}

// PatchBankDetails indicates an expected call of PatchBankDetails.
func (mr *MockISQLServiceMockRecorder) PatchBankDetails(id, bankDetails interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchBankDetails", reflect.TypeOf((*MockISQLService)(nil).PatchBankDetails), id, bankDetails)
}

// PostAccountDetails mocks base method.
func (m *MockISQLService) PostAccountDetails(bankDetails *models.Account) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostAccountDetails", bankDetails)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostAccountDetails indicates an expected call of PostAccountDetails.
func (mr *MockISQLServiceMockRecorder) PostAccountDetails(bankDetails interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostAccountDetails", reflect.TypeOf((*MockISQLService)(nil).PostAccountDetails), bankDetails)
}

// PostBankDetails mocks base method.
func (m *MockISQLService) PostBankDetails(bankDetails *models.Bank) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostBankDetails", bankDetails)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostBankDetails indicates an expected call of PostBankDetails.
func (mr *MockISQLServiceMockRecorder) PostBankDetails(bankDetails interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostBankDetails", reflect.TypeOf((*MockISQLService)(nil).PostBankDetails), bankDetails)
}
