apiVersion: v1
kind: Service        # Type of Kubernetes resource
metadata:
  name: db           # Name of the Kubernetes resource
  labels:            # Labels that will be applied to this resource
    app: db
    role: master
    tier: backend
spec:
  ports:
  - port: 5432       # Map incoming connections on port 6379 to the target port 6379 of the Pod
    targetPort: 5432
  selector:          # Map any Pod with the specified labels to this service
    app: db
    role: master
    tier: backend